blank_issues_enabled: false
contact_links:
  - name: Compass Detroit Community
    url: https://compass-detroit.com/
    about: Join our Compass Detroit community for discussions and support
  - name: General Questions
    url: https://github.com/Compass-Detroit/compass-website/discussions
    about: Ask general questions about the project in our discussions
